name: CalcStack
version: ${project.version}
main: com.example.calcStack.CalcStackPlugin
api-version: '1.13'
load: STARTUP
author: Mr.ling - wling
description: 计算物品堆叠和箱子数量

commands:
  calculate:
    description: 计算物品堆叠和箱子数量
    usage: /<command> <数量> 或 /<command> <物品ID> <数量>
    aliases:
      - calc